name: ci

on: [push]

jobs:
  tests:
    name: Forge Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: dependencies
        run: forge install
      - name: tests
        run: forge test --via-ir

  snapshot:
    name: Forge Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: dependencies
        run: forge install
      - name: check contract sizes
        run: forge build --sizes --via-ir
      - name: check gas snapshots
        run: forge snapshot --check --via-ir